homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 767
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  #customize:
  #  binary_sensor.floorplan:
  #    custom_ui_state_card: state-card-floorplan
  #    config: !include floorplan.yaml 

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
#frontend:
  #extra_html_url:
  #  - /local/custom_ui/state-card-floorplan.html

# Enables configuration UI
config:

hassio:

http:
  api_password: !secret http_password
 #base_url: https://yedgar.duckdns.org:8123
 # cors_allowed_origins:
 #   - http://10.100.102.7
 #   - http://10.100.102.6
 #   - http://10.100.102.8
#ssl_certificate: /ssl/fullchain.pem
#ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google

cloud:

vera:
  vera_controller_url: http://10.100.102.200:3480/
  
prometheus:

#mqtt:
#  broker: 10.100.102.100
  
#device_tracker:
#  - platform: owntracks

#light:
#  - platform: yeelight
#    devices:
#      10.100.102.11:
#        name: Living Room
#        transition: 1000

switch:
  - platform: broadlink
    host: 10.100.102.3
    mac: '34:ea:34:42:aa:3b'
    type: rm_mini
    switches:
      parents_air_con:
        friendly_name: "Parents Air Condition"
        command_on: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
        command_off: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
  - platform: broadlink
    host: 10.100.102.2
    mac: '34:ea:34:42:b6:46'
    type: rm_mini
    switches:
      parents_air_con:
        friendly_name: "Kids Air Condition"
        command_on: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
        command_off: 'JgBgAQABKJMUNhQ3FBITEhYQExMTEhQ3ExIUNxQ3ExITExMSFBITExMSFBIUNhQSFBITEhQSFBITEhQSExMTEhQSExMTNxQ3ExIUEhMTExIUEhMSFBITExMSFBIVERMSFBITExMSExMTAAEFFDcTEhQ3FDYUEhQSExIUNxQ3EzcUNxMSExMTNxQSExMUERQSExMTEhQSExMTEhURExMTEhMTExIUEhMTExITExURExIUEhMTExITExMSFBIUEhMSFBIUEhMSFBITEhQSFBITExMSExMTEhQSExMTEhQSFTUUNxQ3ExIUNxQ2FBITAAEFFBITExMSFBITEhQSExMUERU2FBITEhQSExIUEhQSExMTEhMTExIUEhMTExITExMTExITExMSFBITExMSFBITExMSFBITExMSFBITEhQSFBITEhQSExMTEhQSExMTEhMTEzcUEhQSExIUEhMTExITExMADQUAAAAAAAAAAA=='
  - platform: broadlink
    host: 10.100.102.3
    mac: '34:ea:34:42:b6:56'
    type: rm_mini
    switches:
      parents_air_con:
        friendly_name: "Living Room Air Condition"
        command_on: 'JgC4AGaBQD9AQCEfQR8fISEfIR8hPyAfIR8hH0EfHiEiHyAfIR8hHx8hHyAhHyEfIR8iHyAfIR8gICEfID9CH2CCQj9APyEfQR8hHiIeIR8fQSEfHyEfIUEeIh8fICIfIB8iHyAgICAgHiIfIR8fICEfICAfISEgID5AIGSBQD9BPyAfQCAiHyAfHyAgQCEfHyEfIUEfHyAgICAgIh8eIR8hHyEfIR8gIh8gHyIfHyAiHyEeH0BBH4MADQU=='
        command_off: 'JgC4AGaBQD9AQCEfQR8fISEfIR8hPyAfIR8hH0EfHiEiHyAfIR8hHx8hHyAhHyEfIR8iHyAfIR8gICEfID9CH2CCQj9APyEfQR8hHiIeIR8fQSEfHyEfIUEeIh8fICIfIB8iHyAgICAgHiIfIR8fICEfICAfISEgID5AIGSBQD9BPyAfQCAiHyAfHyAgQCEfHyEfIUEfHyAgICAgIh8eIR8hHyEfIR8gIh8gHyIfHyAiHyEeH0BBH4MADQU=='

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
history_graph: !include graphs.yaml
input_select: !include input_select.yaml
zone: !include zones.yaml
