- platform: group
  name: kidsCoverGroup
  entities:
    - cover.level_3
    - cover.level_4

- platform: group
  name: parentsCoverGroup
  entities:
    - cover.level
    - cover.level_2

- platform: group
  name: kitchenCoverGroup
  entities:
    - cover.level_9
    - cover.level_10

- platform: group
  name: livingRoomCoverGroup
  entities:
    - cover.level_5
    - cover.level_6
    - cover.level_7