
- platform: mqtt
  friendly_name: Outside Temperature
  name: outside_temp
  state_topic: outside_temp
  unit_of_measurement: '°C'
  value_template: '{{ float(value_json.temp ) }}'
 
- platform: mqtt
  friendly_name: Computer Room Temprature Sensor
  name: computerRoomTemp
  state_topic: computerRoom
  unit_of_measurement: '°C'
  value_template: '{{ float(value_json.temp ) }}'

- platform: mqtt
  friendly_name: Computer Room Humidity Sensor
  name: computerRoomHumidity
  state_topic: computerRoom
  unit_of_measurement: '%'
  value_template: '{{ float(value_json.humidity ) }}'

- platform: yr


# Tracking entity to entity
- platform: google_travel_time
  name: phone_to_home
  api_key: AIzaSyC_cxT-E1rFQzWYDnkIKFR_GmzLPuEMgjw
  origin: device_tracker.tal_phone_p
  destination: zone.home

