
- platform: mqtt
  friendly_name: Outside Temperature
  name: outside_temp
  state_topic: outside_temp
  unit_of_measurement: '°C'
  value_template: '{{ float(value_json.temp ) }}'
 
- platform: mqtt
  name: Computer Room Temp
  state_topic: computerRoom
  unit_of_measurement: '°C'
  value_template: '{{ float(value_json.temp ) }}'

- platform: mqtt
  name: Computer Room Humidity
  state_topic: computerRoom
  unit_of_measurement: '%'
  value_template: '{{ float(value_json.humidity ) }}'

- platform: yr


# Tracking entity to entity
- platform: google_travel_time
  name: phone_to_home
  api_key: AIzaSyC_cxT-E1rFQzWYDnkIKFR_GmzLPuEMgjw
  origin: device_tracker.tal_phone_p
  destination: zone.home
  
- platform: history_stats
  name: Watching TV
  entity_id: cover.kids_l_roller_49
  state: 'open'
  type: time
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)}}'
  end: '{{ now() }}'
  

- platform: template
  sensors:
    waterCost:
        friendly_name: "Garden Water Cost"
        value_template: >-   
            {{ states.sensor.watching_tv.state|float *5 *5 }}


