name: My Awesome Home
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - title: Home
    theme: dark-mode
    cards:
      - type: entities
        title: תריסים
        entities:
          - cover.livingroomcovergroup
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_8
          - cover.kitchencovergroup
          - cover.parentscovergroup
          - cover.kidscovergroup

      - type: entities
        title: מטבח
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_9
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_10

      - type: entities
        title: סלון
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_5
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_6
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_7
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_8
          - switch.fibaro_system_fgs223_double_relay_switch_4
          - switch.fibaro_system_fgs223_double_relay_switch
          - switch.fibaro_system_fgs223_double_relay_switch_3
          - switch.fibaro_system_fgs223_double_relay_switch_6
          - switch.philio_technology_corporation_unknown_type0001_id0013_switch

      - type: entities
        title: הורים
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_2

      - type: entities
        title: ילדים
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_3
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_4

      - type: entities
        title: מרתף
        entities:
          - switch.fibaro_system_fgs223_double_relay_switch_2
          - switch.fibaro_system_fgs223_double_relay_switch_5


  - title: UI
    cards:
      - type: picture-elements
        image: /local/first.jpg
        elements:
          - type: state-icon
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_4
            style:
              top: 25%
              left: 28%
            state_image:
              "on": /local/on.png
              "off": /local/off.png
          - type: state-icon
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch
            style:
              top: 60%
              left: 30%
          - type: service-button
            title: Turn lights off
            style:
              top: 95%
              left: 60%
            service: light.turn_off
            service_data:
                entity_id: group.all_lights

  - title: סנסורים
    cards:
      - type: glance
        title: השקייה
        entities:
          - sensor.trees
          - sensor.bushes
          - sensor.water_cost
          - sensor.garden_humidity
          - sensor.realistic_humidity

      - type: glance
        title: מיקום
        entities:
          - device_tracker.iphone__tal
          - device_tracker.talsmacbookpro
          - device_tracker.ortalsiphone

      - type: glance
        title: טמפרטורה
        entities:
          - sensor.temp1
          - sensor.hum1

      - type: glance
        title: וייז
        entities:
          - sensor.homework
          - sensor.workhome