name: My Awesome Home
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - title: Home
    theme: dark-mode
    cards:
      - type: entities
        title: תריסים
        entities:
          - cover.livingroomcovergroup
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_8
          - cover.kitchencovergroup
          - cover.parentscovergroup
          - cover.kidscovergroup

      - type: entities
        title: מזגנים
        entities:
          - switch.living_room_air_con 
          - switch.play_room_air_con
          - switch.parents_fan
          - switch.parents_air_con 
          - switch.kids_fan
          - switch.kids_air_con
          - input_boolean.away

      - type: entities
        title: מטבח
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_9
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_10

      - type: entities
        title: סלון
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_5
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_6
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_7
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_8
          - switch.fibaro_system_fgs223_double_relay_switch_4
          - switch.fibaro_system_fgs223_double_relay_switch
          - switch.fibaro_system_fgs223_double_relay_switch_3
          - switch.fibaro_system_fgs223_double_relay_switch_6
          - switch.philio_technology_corporation_unknown_type0001_id0013_switch

      - type: entities
        title: הורים
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_2

      - type: entities
        title: ילדים
        entities:
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_3
          - cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_4
          - switch.kids_light

      - type: entities
        title: מרתף
        entities:
          - switch.fibaro_system_fgs223_double_relay_switch_2
          - switch.fibaro_system_fgs223_double_relay_switch_5


  - title: UI
    cards:
      - type: picture-elements
        image: /local/first.jpg
        elements:
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_4
            style:
              top: 25%
              left: 28%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch
            style:
              top: 56%
              left: 30%
              width: 5%
            state_image:
              "on": /local/wall-on.png
              "off": /local/wall-off.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_3
            style:
              top: 50%
              left: 55%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png
          - type: image
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch_6
            style:
              top: 35%
              left: 55%
              width: 5%
            state_image:
              "on": /local/on1.png
              "off": /local/off1.png
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_8
            style:
              top: 8%
              left: 31%
              width: 14%
              height: 3%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
          - type: image
            entity: cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_5
            style:
              top: 50%
              left: 10%
              width: 14%
              height: 3%
            state_image:
              "open": /local/cover-on.png
              "closed": /local/cover-off.png
      - type: picture-entity
        entity: switch.fibaro_system_fgs223_double_relay_switch_4
        image: http://farm7.static.flickr.com/6153/6220100622_88e64ec5d8_b.jpg
        state_image:
          "on": http://farm7.static.flickr.com/6220/6220100616_a877f41a66_b.jpg
        title: Livingroom lights
        tap_action: toggle
        
      - type: entities
        title: טלויזיה
        entities:
          - media_player.samsung_tv_remote
        

  - title: סנסורים
    cards:
      - type: glance
        title: השקייה
        entities:
          - sensor.trees
          - sensor.bushes
          - sensor.water_cost
          - sensor.garden_humidity
          - sensor.realistic_humidity

      - type: glance
        title: מיקום
        entities:
          - device_tracker.iphone__tal
          - device_tracker.talsmacbookpro
          - device_tracker.ortalsiphone

      - type: glance
        title: טמפרטורה
        entities:
          - sensor.temp1
          - sensor.hum1

      - type: glance
        title: וייז
        entities:
          - sensor.homework
          - sensor.workhome
  
  - title: אוטומציות
    cards:
      - type: entities
        entities:
          - group.all_automations