name: My Awesome Home
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - title: Home
    theme: dark-mode
    # The cards to show on this view.
    title: Home
    cards:
        # The entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Kitchen
        # The entities here will be shown in the same order as specified.
        entities:
          - cover.level_9
          - cover.level_10
  - title: UI
    cards:
      - type: picture-elements
        image: /local/first.jpg
        elements:
          - type: state-icon
            tap_action: toggle
            entity: switch.switch_5
            state_image:
              "on": /local/on.png
              "off": /local/off.png
            style:
              top: 25%
              left: 28%
          - type: state-icon
            tap_action: toggle
            entity: switch.fibaro_system_fgs223_double_relay_switch
            style:
              top: 60%
              left: 30%
          - type: service-button
            title: Turn lights off
            style:
              top: 95%
              left: 60%
            service: light.turn_off
            service_data:
                entity_id: group.all_lights